---
- name: Make sure we can connect
  ping:
# MySQL
- name: Install MySQL
  apt: name={{item}} state=installed
  with_items:
    - mysql-server-5.6
    - python-mysqldb
- name: Generate new root password
  command: openssl rand -hex 7 creates=/root/.my.cnf
  register: mysql_new_root_pass
# If /root/.my.cnf doesn't exist and the command is run
- debug: msg="New root password is {{ mysql_new_root_pass.stdout }}"
  when: mysql_new_root_pass.changed
# If /root/.my.cnf exists and the command is not run
- debug: msg="No change to root password"
  when: not mysql_new_root_pass.changed
# Secure MySQL and setup root access
- name: Remove anonymous users
  mysql_user: name="" state=absent
  when: mysql_new_root_pass.changed
- name: Remove test database
  mysql_db: name=test state=absent
  when: mysql_new_root_pass.changed
- name: Update root password 
  mysql_user: name=root host={{item}} password={{mysql_new_root_pass.stdout}} 
  with_items: 
    - "{{ ansible_hostname }}" 
    - 127.0.0.1 
    - ::1 
    - localhost 
  when: mysql_new_root_pass.changed
- name: Create my.cnf
  template: src=templates/my.cnf dest=/root/.my.cnf
  when: mysql_new_root_pass.changed
# Setup MySQL for Jira
- name: Create Jira database
  mysql_db: name=jira state=present
- name: Create Jira DB user
  mysql_user: name="jira" host=localhost priv='*.*:ALL' password=jira
  