---
# Add Java dependancy for Jira
- name: Add Java 8 repository
  apt_repository: repo='ppa:webupd8team/java'
- name: Agree to oracle license
  debconf: name=oracle-java8-installer question=shared/accepted-oracle-license-v1-1 vtype=select value=true
- name: Install Java 8
  apt: name=oracle-java8-installer force=yes

# Copy files into place
- name: Copy Jira file
  copy: src=files/{{ jira_filename }}-{{ jira_version }}.bin dest={{ jira_user_home_dir }}/{{ jira_filename }}-{{ jira_version }}.bin 
- name: Make file executable
  file: 
    path: "{{ jira_user_home_dir }}/{{ jira_filename }}-{{ jira_version }}.bin"
    mode: 0755
- name: Copy response file into place
  template: src=response.varfile dest={{ jira_user_home_dir }}
- name: Copy MySQL driver
  copy: src=files/mysql-connector-java-5.1.44.tar.gz dest={{ jira_user_home_dir }}

- stat: path={{ jira_user_home_dir }}/jira/bin/start-jira.sh
  register: st

# Execute unattended install of Jira
- name: Unattended install of Jira
  shell: "{{ jira_user_home_dir }}/{{ jira_filename }}-{{ jira_version }}.bin -q -varfile {{ jira_user_home_dir }}/response.varfile"
  when: not st.stat.exists

# Copy MySQL JDBC driver into place
- name: Unarchive driver
  unarchive: src={{ jira_user_home_dir }}/mysql-connector-java-5.1.44.tar.gz dest={{ jira_user_home_dir }} copy=no
- name: Move driver into place
  copy: remote_src=true src={{ jira_user_home_dir }}/mysql-connector-java-5.1.44/mysql-connector-java-5.1.44-bin.jar dest={{ jira_user_home_dir }}/jira/lib

# Copy database configuration into place
- name: Copy database file into place
  template: src=dbconfig.xml dest={{ jira_home }}

# Start the Jira service
- name: enable jira service
  service: name=jira enabled=true state=started
